### ISSUE TITLE
Can't get passed Final Step.

### ISSUE THREAD

**Issue by Highpowerrp** [Madpeterz/StreamAdmin#1]
Describe the bug
A clear and concise description of what the bug is. I can not get the final step in setting up. I am able to create and connect to the database to see all the tables created. however, I can not get the Final step to creating a staff user.
the error I get is "unable to update staff entry" https://prnt.sc/v2sy93
To Reproduce

Go to docker pull container and launcher it
Fill out the database connection info
test and it passes then it install and it passes
The final setup asks for staff info that I can't pass
see link for screenshot of error https://prnt.sc/v2sy93
Expected behavior

Make me an account to login with,
Screenshots
https://prnt.sc/v2sy93

Hardware (please complete the following information):

OS: ubuntu 16.04
Version: streamadmin_r7
Running in docker: Yes
Running as Linux service: Yes
Additional context
Thanks for everything maybe you can help me with a Readme file or a wiki on setting up some server and bot to work together. thank <3

**Comment by Madpeterz** [comment]
Hi there are you using the docker-compose to create the docker instance as there are required env values if you running in docker or you risk losing your settings every time you restart the container.

**Comment by Madpeterz** [comment]
Note:
        also this commit fixs a issue with updates that i broke: https://github.com/Madpeterz/StreamAdmin/commit/496b8eca4e460c198d22273d424fa9b1bb2a12d6

**Comment by Highpowerrp** [comment]
Hello, I am using portainer.io and running the container in docker, I am able to get it installed and working this time. However, I can't seem to get my centova cast 3 servers to connect any ideas what I may be doing wrong. here a few screenshots. https://prnt.sc/v3cs4u https://prnt.sc/v3csnh, Thanks for your help

**Comment by Madpeterz** [comment]
Hi there, please make sure you add http:// or https:// to the start of the api url.
you can tell the api has connected correctly when your at the dashboard and the server load status updates
