### ISSUE TITLE
Reseller Version

### ISSUE THREAD

**Issue by Scotspaul** [Madpeterz/StreamAdmin#101]
Would it be possible to have what version of vendors in Resellers  ppl are using?
If they need to upgrade to 1.0.2.4  for example
with many boards out there its difficult to see who needs updating

**Comment by tj1uk** [comment]
this should only be enforced if a major change, other wise its going to piss a lot of resellers off keep sending them new vendors every 5 minutes, its ok if only have 1 or 2 but when you have a lot of resellers it becomes a hassle.

**Comment by Madpeterz** [comment]
2.0.0.0 only adds support to enforce min version later on it will have support for more granularity.
so that for example the api could be on version 2.0.1.5, the buy code has not changed from 2.0.0.0 so it would still support this older version.
