### ISSUE TITLE
Hud Dialog Amounts Change Request

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/StreamAdmin#102]
Please change the payment selection dialog buttons in HUD menu to indicate "words" with corresponding amounts as shown below:

If a monthly package: 1 Month, 2 Months, 3 Months, 4 Months
If Weekly: 1 Week, 2 Weeks, 3 Weeks, 4 weeks
If 3-day: 3 days, 6, days, 9 days, 12days
If Daily: 1 Day, 2 Days, 3 Days, 4 Days
etc.

**Comment by Madpeterz** [comment]
the wording will now work as follows
if package adds 7 days it will be marked as "Week" or "Weeks"
if package adds 31 days it will be marked as "Month" or "Months"
otherwise it will appear as "Day" or "Days"

**Comment by Madpeterz** [comment]
When using the renew prim the following text is now added to the output
"Each renewal of L$100 gives 10 Day's"

**Comment by Madpeterz** [comment]
if the package gives a multiple of 7 it will use the word "Week" / "Weeks"
if the package gives a multiple of 31 it will use the word "Month" / "Months"
otherwise it will use "Day" / "Days"

**Comment by Madpeterz** [comment]
Feature is now supported as of 2.0.0.0

for the hud it gives text buttons, for renewals / proxy pay adds the given message.
