### ISSUE TITLE
Hud and Reseller Updater

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/StreamAdmin#104]
Is it possible to have a server updater (or call it something else) created for this system whereby the server (in world) see what version a reseller and/or HUD is, and if needed is automatically updated?

I assume we would need to put the updated item(s) into the server prim and the triggers happen ONLY when someone wears the HUD, or a reseller vendor is active in world .

The scan should happen each time the HUD is worn, and maybe once or twice a day for the reseller vendor.

This will facilitate and potentially satisfy issue #101 without the need for "enforcement".

I tried using the caspervend system for this and it really sucks. Besides, it would be nice have something dedicated to this system as opposed to one system doing things for 10s of 1000s merchandizing items.

**Comment by Madpeterz** [comment]
This would be out of scope for Streamadmin more for a vender system but I don't see why I cant make a 2nd web thinge that does this.
