### ISSUE TITLE
v3.3.1 upadate

### ISSUE THREAD

**Issue by maletazul** [Madpeterz/StreamAdmin#126]
Hi,

i have an  old ver 3.3.1 of stream admin.
what is the best way, full install or updating?

Txs,
Luis
[Updates_R3.3.1.zip](https://github.com/Madpeterz/StreamAdmin/files/11065799/Updates_R3.3.1.zip)

**Comment by Madpeterz** [comment]
wow thats a old version, R5 was the last version that can update to current
