### ISSUE TITLE
Markeplace Cupons

### ISSUE THREAD

**Issue by maletazul** [Madpeterz/StreamAdmin#127]
The basic idea is create a copum per server, and when you buy in the marketplace you receave only the cupon code and then you go to the vender and he gives a stream without asking the payment

just using the code

**Comment by Madpeterz** [comment]
Not sure if this is how you want it but is the first system we are getting

1: Marketplace listings can be used to credit the account
2: credit is refunded when the customer buys/renews a stream at a owner vendor only
[later on I plan to add support to pay with credits so it can be used at all locations]
[note: if a customer would pay with credit the reseller does not get a cut]
3: the customer can opt in (per rental) for automated renewals when a stream switchs to expired.

it will require you to have setup your marketplace ANS to support this (wiki entry soon)
if you use ANS for other products like casperVend for example you will need to setup the Relay (wiki entry soon)
so you can support both systems.

**Comment by Madpeterz** [comment]
done as per 2.0.1.1

**Comment by maletazul** [comment]
Hey Pete,

I lost my discord, can you add d.dvs1 ?

Melhores Cumprimentos,

Maletazul Lda
Luis Silva
+351.916211270
www.maletazul.pt<x-msg://832/www.maletazul.pt>
www.facebook.com/maletazul<x-msg://832/www.facebook.com/maletazul>


CCNA – CCDA - VCP – VSTP – VMTSP - VMSP - EMC´s VNX – MCSE
***@***.***
