### ISSUE TITLE
Time Stamp Issue on V2

### ISSUE THREAD

**Issue by longhorns709** [Madpeterz/StreamAdmin#129]
**Notes**
Changing the time zone in the config doesn't change the time stamp that the bot issues out. 

**Describe the bug**

**To Reproduce**
change the time zone in the config and request for a new notecard. check the time it will be off

**Expected behavior**
The notecard should be sent with the timezone's time selected in the config

**Screenshots**
https://i.imgur.com/a2OTtMv.png

**Comment by Madpeterz** [comment]
fixed in 2.0.0.0 but it will also want a update to the bot to remove the datetime it applies on the end (already done on the events version)
