### ISSUE TITLE
Changing of the Rental Notice gives error V2

### ISSUE THREAD

**Issue by longhorns709** [Madpeterz/StreamAdmin#130]
**Describe the bug**
When changing the text in the notice page it accepted the first save and from there on it shows object object in the top right.

**To Reproduce**
Just change the Notice info and it bugs out.

**Expected behavior**
Should save the information and update there after then saved. 

**Screenshots**

https://i.imgur.com/eVHQAY3.gif

**Comment by Madpeterz** [comment]
fixed by: https://github.com/Madpeterz/yetonemorephpframework/commit/e29831968b5744b23a5998fed44cd2928422fec1

should be corrected in the next update tomo but I sleep now  ^+^
