### ISSUE TITLE
Options to set the texture faces V2

### ISSUE THREAD

**Issue by longhorns709** [Madpeterz/StreamAdmin#132]
**Is your feature request related to a problem? Please describe.**
I would like to be able to pick that FACE the rental will use. Example Face = 6;

**Describe the solution you'd like**
This is will allow to use less prims/linking of objects and would look better over not having to worrie about that extra prim 

**Describe alternatives you've considered**
Tried link a prim and it works but some time that extra prim hurts when renting from places with low prim counts.

**Additional context**
None

**Comment by Madpeterz** [comment]
will be supported as part of https://github.com/Madpeterz/StreamAdmin/issues/136
