### ISSUE TITLE
Shorten IM & Notecard Tags

### ISSUE THREAD

**Issue by longhorns709** [Madpeterz/StreamAdmin#15]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use over 200 Characters in tags out of the 800 Character limit.
**Describe the solution you'd like**
 have shorter tags please.
**Describe alternatives you've considered**

**Additional context**

**Comment by Madpeterz** [comment]
The following tags have been added that are shorter than the defaults but about the size of the content they are being swapped for

AVATAR_FIRSTNAME => FirstName
AVATAR_LASTNAME => LastName
RENTAL_EXPIRES_DATETIME => ExpiresAt
RENTAL_TIMELEFT => TimeLeft
STREAM_PORT => PortNum
STREAM_ADMINUSERNAME => AdminUsername
STREAM_ADMINPASSWORD => AdminPassword
STREAM_DJPASSWORD => DjPassword
STREAM_MOUNTPOINT => MountPoint
PACKAGE_NAME => Package
PACKAGE_LISTENERS => Users  
PACKAGE_BITRATE => Kbps 
PACKAGE_AUTODJ => AutoDJ
PACKAGE_AUTODJ_SIZE => Disk
PACKAGE_UID => PackUID
RENTAL_UID => RentUID

**Comment by Madpeterz** [comment]
the old values will remain and will continue to be supported
