### ISSUE TITLE
Vending trees selection.

### ISSUE THREAD

**Issue by Highpowerrp** [Madpeterz/StreamAdmin#16]
**Describe the bug**
 When trying to select a stream from the vending Tree unit it won't allow you to select Icecast or Shoutcast packages it only gives you the first stream package added to the tree list.

**Comment by Madpeterz** [comment]
Is this happening on the website or in secondlife?

**Comment by Madpeterz** [comment]
Detail: 
when creating a tree that has shoutcast and icecast mixed it should give that as the first option.
