### ISSUE TITLE
Static notecards on starting rentals

### ISSUE THREAD

**Issue by JessieCrisp-SL** [Madpeterz/StreamAdmin#22]
Not sure if this is already in place or even if it is doable. 

But I was thinking that when a customer rents an AutoDj package besides just sending them their stream info via notecard, the bot or system could also send them a notecard with further information on it (ie.. how to upload music via FTP or even how to make a live DJ account and how to set up their encoder.) 

1. New Client rents AudoDJ stream
2. Stream Information is sent via IM and Notecard.
3. More information is sent via Notecard only, but only if they rent an AutoDj stream.

Anyway just a though.

Thanks

DJLisa

**Comment by Madpeterz** [comment]
would you want this to be a dynamic  notecard (ie you can edit the content online but you will need a bot)
or static?

**Comment by JessieCrisp-SL** [comment]
I think it could be static, just more of information on how to set stuff up or where to look at in Centova for where to do it.

**Comment by Madpeterz** [comment]
ok I will set it up as follows

1: Add a notecard to the "Notices&Notecards" box.
2: Select 2 notecards from the packages menu
"Welcome" notecard
"Setup guide" notecard

the welcome notecard is only sent when you rent a stream (and do not currently have a active rental)
the setup guide is sent every time.

by default these will be set to "None" and will be "OptIn" for usage

**Comment by JessieCrisp-SL** [comment]
Sounds awesome thank you.

**Comment by Madpeterz** [comment]
this request is now supported as of 1.0.1.9
