### ISSUE TITLE
End User HUD

### ISSUE THREAD

**Issue by AudioSource** [Madpeterz/StreamAdmin#26]
Would love to see the old user HUDS come back.

A HUD we can give to our clients that allow them to:

1. See their stream info. (Either on the HUD or the hud/bot sends them an IM or notecard)
2. Renew their stream from anywhere on the grid.
3. Get the URL for the store. (Not needed but would be nice)
4. Button to link them to my Discord channel (would either invite them to the server or open it if they are already a member.)

Best would be a Modified HUD (or at least the scripts that were transfer) so we could make our own HUDS. This would allow users to customize what they really wanted their customers to use (like if they didn't have a discord, or didn't want to offer payments.)

Thanks :)

**Comment by Madpeterz** [comment]
done and done.
