### ISSUE TITLE
Expired Clients

### ISSUE THREAD

**Issue by AudioSource** [Madpeterz/StreamAdmin#34]
**Describe the bug**
Unable to remove expired clients in bulk when clicking on the "Expired" button on dashboard.

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Red Expired Button'

**Expected behavior**
I might be wrong, but didn't there use to be an option to do bulk removals of expired clients?
![Expired](https://user-images.githubusercontent.com/54406633/123299089-c81b6980-d4de-11eb-8e5c-603b4c648cb0.PNG)

**Comment by Madpeterz** [comment]
Issue confirmed and fixed.
