### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by LordFader** [Madpeterz/StreamAdmin#39]
Hello,
I'm interested in the development of this application.
I'm not a programmer but a end user.
Could you write some instructions how to install this application?

As a server I'm using a Raspberry Pi 4 Model B Rev 1.2, 4 cores 
- OS Ubuntu Linux 21.04 (server)
- Apache version 2.4.46
- MariaDB version 10.5.12
- PHP 7.4

Didn't decide yet if I'm going to install Libretime or Azuracast...

Looking forward to rent a VPS.

Thank you so much for your time.

**Comment by Madpeterz** [comment]
Hello this software pairs with a paid for system in Secondlife, without that half it is pointless to have.

**Comment by Madpeterz** [comment]
you can reach me in secondlife as: Madpeter Zond.
