### ISSUE TITLE
Auto Group invite

### ISSUE THREAD

**Issue by XinoKnave** [Madpeterz/StreamAdmin#47]
When a people buy a product or rent one land they can recive the group. 
example:
Land Admin Request:
- When a customer buy the land, they can recive the Customer Support Group ( Same to the OLD SecondBot )

Stream Admin Request:
- When a people buy one new stream the bot can send the Customer Support Group ( Same to the OLD SecondBot )

**Comment by Madpeterz** [comment]
Legacy software: Landadmin is not supported.

Working on the Streamadmin side now
- Global enable with per package opt out.

**Comment by Madpeterz** [comment]
In testing

**Comment by Madpeterz** [comment]
added in the next update
