### ISSUE TITLE
Please add the the option to change SA7 Logo?

### ISSUE THREAD

**Issue by Highpowerrp** [Madpeterz/StreamAdmin#5]
Hello, I would like to know if we may have the option to brand the panel with our own logo. Thanks :)

**Comment by Madpeterz** [comment]
Can do I will add it as part of the AzureCast Branch update (its under way)

**Comment by Madpeterz** [comment]
https://github.com/Madpeterz/StreamAdmin/wiki/Customize-images-(docker-only)

**Comment by Madpeterz** [comment]
This is supported in the next update via writing a base64 encoded png to the database

1: Convert image to base64
https://www.base64-image.de/

2: Edit DB and set the following flags
A- CustomLogo: True
B- CustomLogoBin: Base64 string
inside the slconfig table

notes: this is only for docker users, classic style can just edit the png directly.
