### ISSUE TITLE
Proper Button display on Tree Vendor

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/StreamAdmin#50]
Add days to tree vendor selection:
1 Day
3 Days
7 Days
30 Days

**Comment by Madpeterz** [comment]
fixed with website update
1 day = "24 hours"
7 days = "One week"
14 days = "Two week's"
21 days = "Three week's"
28 days = "Four week's"
31 days = "Monthly"

any other amount = "X Day's"
