### ISSUE TITLE
Add Back button to ALL vendors menus

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/StreamAdmin#51]
All vendor:  Add back button to the menu in case customer made the wrong selection

**Comment by Madpeterz** [comment]
- Requires LSL update

Renew: Exit button
Tree: Right click touch [when at the pay step]
Proxy: Touch to reopen menu and Exit button
Details: Touch to reopen menu and Exit button
Buy: Touch [owner or current user] to return to standby
