### ISSUE TITLE
Details Vendor Button Selection

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/StreamAdmin#53]
Details Vendor:
Change Selection Box:
From 
1. e86a4019 (10404)
2: 39ab9693 (19102)
3: 610ac038 (20368)
4: 61b3f8f5 (8102)

To:
Port: 10404 (e86a4019)
Port: 19102 (39ab9693)
Port: 20368 (610ac038)
Port: 8102 (61b3f8f5)

**Comment by Madpeterz** [comment]
Done, requires LSL update
