### ISSUE TITLE
Send IM for any sale or renewal

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/StreamAdmin#60]
Need for the ability to have the system send an IM to the owner whenever there is a sale or renewal - much like S4 had.

This is crucial for knowing when someone has paid for the service, especially in cases where the server was suspended, and after renewal, the server needs to be unsuspended. This is a must-have and should be high on the list of priorities.

**Comment by Madpeterz** [comment]
the new EventQ update covers this
