### ISSUE TITLE
Grace Period (API Related)

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/StreamAdmin#69]
Allow an owner defined grace period, or bypass before the API will suspend a server. 

Grace period should be defined with a value of "Days". 

An option to bypass or not should also be included to bypass the auto suspension altogether. Perhaps a checkbox?

Both items should be allowed to be defined at package or server creation, with ability to edit it on a per server basis once the server is leased (in use).

**Comment by Madpeterz** [comment]
this is now underway flow as follows


Packages set if API auto suspend is enabled or not for all streams in that package.
and if enabled what the delay [in hours] will be.

-> 

Streams can override this setting by using the "Allow Suspend" flag and setting it to No.

->

Rentals [when they expire]

if they would have been suspended now get a "Pending suspend" flag set
and a unixtime of then to apply the suspend.

->

A new server object will be required to maintain the rentals that have the Pending suspend event enabled so
when the time comes it pushs the event over to the API for the server.

**Comment by Madpeterz** [comment]
done dfcd8b0c

will require a new SL object: ClientAutoSuspend
to look after this.
