### ISSUE TITLE
Hud Request: Remaining time

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/StreamAdmin#70]
Please add a feature to the HUD where the remaining time is displayed.

While I love the fact that when using a bot, you can have the details, including expiration date come to the user in 3 fashions, I think  a button for remaining time (Time Left) would be more efficient

**Comment by Madpeterz** [comment]
Done

after you select a rental
```
Madpeter Zond's 'streamadmin R7 Hud v1.0.2.4'
Rental: 2a286a78
Timeleft: 30 days, 23 hours
 What do you want todo?
 ```
