### ISSUE TITLE
Time left on Stream Admin Account

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/StreamAdmin#74]
Request, if possible, the time left on the Stream Admin account to be on the dashboard.  Does not need to be a countdown, just how much time is left as of each time you go to the dashboard.

**Comment by Madpeterz** [comment]
hmm that seems like a good idea I could even move the code entry over to the website and have the servers download it.
- it would still be checked in SL just then if you get a new token you wont have to edit/login to SL to update it.

so on the homepage [right side of dashboard]
- Licenced paid until:  XXXX 

and you can click it to enter a new code.

**Comment by Madpeterz** [comment]
Phase 1 is done you can now store the key on the website and it will display info about it.
notes:
the key format has been extended so I can add a checkSum the website can use to make sure the key is vaild.
old style keys will continue to work in SL but will need to be reissued to use on the site.

**Old format**

- Key:ExpiresUnixTime

**New format**

- Key:ExpiresUnixTime:WebCheckSum
