### ISSUE TITLE
Tree Vendor menu items

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/StreamAdmin#75]
Currently, tree vendor shows 
1 - # of listeners needed
2 - how much do you want to pay

It should be as follows:

1 - Plan (Time) i.e. Daily, 3-day, Weekly, Monthly (depending on the package) (each with own button)
2 - How many listeners?
3 - How much space? (for autodj Only)
4 - Pay vendor (with a summary at top of the menu.

The customer then pays the vendor and thus end of transaction

**Comment by Madpeterz** [comment]
Question flow updated to as follows:

renewal period -> listeners -> GB do you need for auto DJ -> what Bitrate -> What software -> what cost?

the questions will auto end if it gets a single match at any stage.

as a bonus I managed to improve the Q system so it is a lot faster now as a bonus :P
