### ISSUE TITLE
Add Additional link to edit stream details from Client

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/StreamAdmin#77]
Need to be able to see/edit stream details from within the client list.

When clicking on the CLient UID, there should be a link on the next page for that client port to be able to edit stream details.

Makes upgrades/downgrades easier to manage

**Comment by Madpeterz** [comment]
seems like a good idea I will add it

**Comment by Madpeterz** [comment]
https://github.com/Madpeterz/StreamAdmin/issues/79
