### ISSUE TITLE
Sale Checks for Existing Customer

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/StreamAdmin#81]
When buying a new server, have the system check to see if the customer already has a server that is working,

If they have a working server, have the menu say "You currently have a stream with us, are you sure you want to purchase a new one?"  [Yes, No]

If they answer Yes then proceed with the sale

If they answer no, then have the blue menu direct them to the "Renew Vendor in the Store"

**Comment by Madpeterz** [comment]
Presales checks have been added for Buy and Tree venders.
