### ISSUE TITLE
Notices - option to enable or disable

### ISSUE THREAD

**Issue by tj1uk** [Madpeterz/StreamAdmin#89]
Since notices can't be deleated  when customers are on that time remaining which is most of the time, please add ability to enable or disable the notices we want to.

**Comment by Madpeterz** [comment]
The following options will be added

- Disable messages from this notice level: [Yes/No] (Default no)
- DIsable this notice level: [Yes/No] (Default no)

if a notice level is marked as disabled clients will skip this notice (good for emptying it out) and then removing it later.

**Comment by Madpeterz** [comment]
done [dev @ c006bf61]
