### ISSUE TITLE
& days remaining incorrect

### ISSUE THREAD

**Issue by kahfluie** [Madpeterz/StreamAdmin#90]
Many customers are showing as 7 days status when in fact they have far more.

This needs to be correct quickly to avoid customers getting these reminders when they are not correct.

![d19078ae40fe092951f4f305c141efb5](https://user-images.githubusercontent.com/74793574/135947669-35ef125b-edb0-4fde-8bd9-78da45ff2b8b.png)

**Comment by Madpeterz** [comment]
1: When buying a stream it is incorrectly setting the notice level to 7 day notice (skipping active) so the active notice level is missed.
2: Renewing does not seem to correct this.

while they will not incorrectly get the 7 day notice, it will lead to them not getting the 7 day notice when it is due.

**Comment by Madpeterz** [comment]
Notes: editing the rental adding an hour corrects the incorrect notice level but still this does need to be fixed.

**Comment by Madpeterz** [comment]
fixed with a optional image update on latest with tests
